
---
  - name: Play1
    hosts: webservers
    tasks:
      - name: Execute command 'date'
        command: date
      - name: Install apache2 on the server
        apt:
           name: apache2
           state: present
      - name: Start Web Server
        service:
             name: apache2
             state: started
      - name: Copy index html to webservers
        copy:
          src: /src/index.html
          dest: /var/www/html/index.html
